alias n="pnpm start"
alias nc="pnpm run commit"
alias nd="INSTANCE=1 pnpm run dev"
alias rs="INSTANCE=1 pnpm run dev"
alias nb="INSTANCE=1 pnpm run build"
alias ndd="PORT=3001 config__server__port=8081 INSTANCE=1 pnpm run dev"
alias nds="INSTANCE=1 pnpm run dev:server"
alias ndc="pnpm run dev:cra"
alias ndt="pnpm run test -- -- --watch"
alias ntw="pnpm run test -- -- --watch"
alias nt="pnpm test"
alias nu="npm-check -uE"
alias projects="~/bash/bash/nodejs/projects.js && ~/bash/bash/git/gls.js"
#alias nu="yarn upgrade-interactive --latest"
alias ns="pnpm run storybook"
alias np="pnpm run release"
alias npp="pnpm run release:yes"
alias nw="pnpm run watch"
alias nr="rm -f package-lock.json && pnpm install"
alias nri="rm -rf node_modules && pnpm install"
alias nrf="rm -f package-lock.json && rm -rf node_modules && pnpm install"
#alias nr="rm -rf yarn.lock && rm -rf node_modules && yarn"
alias nl.="find node_modules -maxdepth 3 -type l | egrep '^node_modules/[^\.]'"
alias nl="find . -maxdepth 5 -type l | egrep 'node_modules/[^\.]' | grep -v /\.bin"
alias nv="cat package.json | grep version"
alias nremove="find . -maxdepth 4 -type d -name 'node_modules'"
alias nremoveyes="find . -maxdepth 4 -type d -name 'node_modules' | xargs rm -R"
alias gstatus="find . -maxdepth 1 -type d | xargs "
# alias nl="find . -maxdepth 5 -type l | egrep 'node_modules/[^\.]' | grep -v /\.bin | xargs ls -l | xargs cut -d' \./' -f 2"

#alias nl="find node_modules -maxdepth 2 -type l | cut -d'/' -f 2"